### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Auster-1** [romdotdog/grayjay-bandcamp#1]
APK version of Grayjay, and Android used is a vanilla ROM.

Using the QR code option, and this error is thrown:

```Version information (version_name = 253, version_code = 253, flavor = stable, build_type = release)
Device information (brand= Xiaomi, manufacturer = Xiaomi, device = sweet, version-sdk = 33, version-os = )

(e, ExceptionActivity, 2024-09-01 11:24:18): Uncaught exception ("Unknown Context"): Illegal base64 character 3c

java.lang.IllegalArgumentException: Illegal base64 character 3c
 at java.util.Base64$Decoder.decode0(Base64.java:714)
 at java.util.Base64$Decoder.decode(Base64.java:526)
 at java.util.Base64$Decoder.decode(Base64.java:549)
 at com.futo.platformplayer.SignatureProvider$Companion.verify(SignatureProvider.kt:29)
 at com.futo.platformplayer.api.media.platforms.js.SourcePluginConfig.validate(SourcePluginConfig.kt:167)
 at com.futo.platformplayer.views.sources.SourceHeaderView.loadConfig(SourceHeaderView.kt:109)
 at com.futo.platformplayer.activities.AddSourceActivity.loadConfig(AddSourceActivity.kt:186)
 at com.futo.platformplayer.activities.AddSourceActivity.access$loadConfig(AddSourceActivity.kt:34)
 at com.futo.platformplayer.activities.AddSourceActivity$loadConfigUrl$1$4.invokeSuspend(AddSourceActivity.kt:177)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7893)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4fdba9d, Dispatchers.IO]```

**Comment by ThunderHen** [comment]
I'm having the same problem.

**Comment by romdotdog** [comment]
Whatever QR code you're using is not my QR code. I cannot fix it.

This project was not meant to be installed in the first place, but I'll put it on my light maintenance list since people seem to be using it.

**Comment by ThunderHen** [comment]
Qr code is listed here  https://grayjay-sources.github.io/ btw. Thank for makeing the project even if you did intend for people to use it.

**Comment by romdotdog** [comment]
I'm not familiar with the QR code feature. I tested the plugin and it still seems to be working. If any of the folks over at the sources repository want me to make a specific change to this repository, then I will implement that change. Otherwise, this issue seems out of scope for this repository.

Please reopen if there is any new information.

**Comment by ThunderHen** [comment]
Version information (version_name = 262, version_code = 262, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a12u, version-sdk = 31, version-os = samsung/a12usq/a12u:12/SP1A.210812.016/A125USQU6CWG2:user/release-keys)

(e, ExceptionActivity, 2024-09-07 19:16:30): Uncaught exception ("Unknown Context"): Illegal base64 character 3c

java.lang.IllegalArgumentException: Illegal base64 character 3c
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.futo.platformplayer.SignatureProvider$Companion.verify(SignatureProvider.kt:29)
	at com.futo.platformplayer.api.media.platforms.js.SourcePluginConfig.validate(SourcePluginConfig.kt:169)
	at com.futo.platformplayer.views.sources.SourceHeaderView.loadConfig(SourceHeaderView.kt:109)
	at com.futo.platformplayer.activities.AddSourceActivity.loadConfig(AddSourceActivity.kt:186)
	at com.futo.platformplayer.activities.AddSourceActivity.access$loadConfig(AddSourceActivity.kt:34)
	at com.futo.platformplayer.activities.AddSourceActivity$loadConfigUrl$1$4.invokeSuspend(AddSourceActivity.kt:177)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@33899e2, Dispatchers.IO]

**Comment by ThunderHen** [comment]
Installing the plugin crashes unless I install it using development server link is  grayjay://plugin/https://raw.githubusercontent.com/romdotdog/grayjay-bandcamp/main/config.json as for the qr code it just uses https://raw.githubusercontent.com/romdotdog/grayjay-bandcamp/main/config.json

**Comment by romdotdog** [comment]
Oh, I think I understand what's happening. Does it work with the new commit?

**Comment by ThunderHen** [comment]
Yes thank you.
